language: android

jdk:
  - oraclejdk8

env:
    global:
        - NDK_VERSION=r15b
        - NDK_CCACHE=ccache
        - GOROOT_BOOTSTRAP=$GOROOT
        - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
        - SBTPATH=$HOME/.sbt
        - PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

scala:
    - 2.11.11

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "*.lock" | xargs rm

cache:
    directories:
        - $HOME/.ivy2
        - $HOME/.sbt

android:
    components:
        - tools
        - build-tools-26.0.0
        - extra-android-m2repository
        - extra-google-m2repository

install:
    - sudo apt-get -y install ant 
    - bash travis-ci/setup.sh
