language: android

jdk:
  - oraclejdk8

env:
    global:
        - NDK_VERSION=r15b
        - NDK_CCACHE=ccache
        - GOROOT_BOOTSTRAP=$GOROOT
        - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
        - SBTPATH=$HOME/.sbt
        - PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

scala:
    - 2.11.11

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "*.lock" | xargs rm

cache:
    directories:
        - $HOME/.ivy2
        - $HOME/.sbt

android:
    components:
        - tools
        - build-tools-26.0.0
        - extra-android-m2repository
        - extra-google-m2repository

install:
    - sudo apt-get -y install ant sbt
    - sudo brew install android-ndk android-sdk
    - export ANDROID_HOME=/usr/local/Cellar/android-sdk/$version
    - export ANDROID_NDK_HOME=/usr/local/Cellar/android-ndk/$version
    - echo "y" | android update sdk --filter tools,platform-tools,build-tools-23.0.2,android-23,extra-google-m2repository --no-ui -a
    - echo "y" | android update sdk --filter extra-android-m2repository --no-ui --no-https -a
    - git submodule update --init
    - ./build.sh
    - sbt clean android:package-release
